config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :products

  root 'products#index'

  get 'addtocart/:product_id', to: 'purchases#add_to_cart', as: 'add_to_cart'

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    user ||= User.new(role: 0)
        if user.admin?
            can :manage, :all
        else
          can :read, :buy, :all
        end
    
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/product.rb
class Product < ActiveRecord::Base
	include PgSearch
	extend FriendlyId

	has_many :purchases
	
	mount_uploader :imagen, ImagenUploader

	friendly_id :name, use: [:slugged, :finders]

	pg_search_scope :search_by_name, against: [:name]

  def bought_by?(user)
    self.user_purchases.include? user
  end
end

app/models/purchase.rb
class Purchase < ActiveRecord::Base
  belongs_to :user
  belongs_to :product
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :products, through: :purchases

  enum role: [:guest, :admin]
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

	before_action :configure_permitted_parameters, if: :devise_controller?

    protected

    def configure_permitted_parameters
      devise_parameter_sanitizer.for(:sign_up) << :name
      devise_parameter_sanitizer.for(:account_update) << :name
    end
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  	protect_from_forgery with: :exception
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    if params.key?(:query) && !params[:query].empty?
      @products = Product.search_by_name(params[:query]).page(params[:page]).per(10)
    else
      @products = Product.all.page(params[:page]).per(10)
    end

    respond_to do |format|
      format.html
      format.js
    end
  end

  # GET /products/1
  # GET /products/1.json
  def show
    @purchase = Purchase.new
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end



  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :description, :category, :price, :initial_stock, :current_stock, :imagen)
    end
end

app/controllers/purchases_controller.rb
class PurchasesController < ApplicationController

	 def add_to_cart
    render json: params
    @product = Product.find(params[:product_id])
    @user = current_user
    @purchase = Purchase.new(user: @user, product: @product)
    p @purchase
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/purchases_helper.rb
module PurchasesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Ecommerce</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render 'shared/navbar' %>

<%= yield %>

</body>
</html>

app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="nombre_prod">
    <%= f.label :name, 'Nombre' %><br>
    <%= f.text_field :name %>
  </div>
  <div class="descripcion_prod">
    <%= f.label :description, 'Descripción' %><br>
    <%= f.text_area :description %>
  </div>
  <div class="categoria_prod">
    <%= f.label :category, 'Categoría' %><br>
    <%= f.text_field :category %>
  </div>
  <div class="precio_prod">
    <%= f.label :price, 'Precio' %><br>
    <%= f.number_field :price %>
  </div>
  <div class="stock_inicial_prod">
    <%= f.label :initial_stock, 'Stock Inicial' %><br>
    <%= f.number_field :initial_stock %>
  </div>
  <div class="stock_actual_prod">
    <%= f.label :current_stock, 'Stock Actual' %><br>
    <%= f.number_field :current_stock %>
  </div>

   <div class="imagen_prod">
    <%= f.label :imagen, 'Imagen del producto' %><br>
    <%= f.file_field :imagen %>
  </div>

  <br>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form' %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Lista de productos</h1>

<table>
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Descripción</th>
      <th>Categoría</th>
      <th>Precio</th>
      <th>Stock</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.name %></td>
        <td><%= product.description %></td>
        <td><%= product.category %></td>
        <td><%= product.price %></td>
        <td><%= product.current_stock %></td>
        <td><%= image_tag(product.imagen) %>        
        <td><%= link_to 'Revisa más :)', product %></td>
        <% if can? :update, product %>
          <td><%= link_to 'Edit', edit_product_path(product) %></td>
        <% end %>
        <% if can? :delete, product %>
          <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<% if can? :create, Product %>
<%= link_to 'New Product', new_product_path %>
<% end %>

app/views/products/new.html.erb
<h1>Nuevo Producto</h1>

<%= render 'form' %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Producto:</strong>
  <%= @product.name %>
</p>

<p>
  <strong>Descripción</strong>
  <%= @product.description %>
</p>

<p>
  <strong>Categoría:</strong>
  <%= @product.category %>
</p>

<p>
  <strong>Precio:</strong>
  <%= @product.price %>
</p>


<p>
  <strong>Stock:</strong>
  <%= @product.current_stock %>
</p>

<p>
 <%= image_tag(@product.imagen.url) %>
</p>

<%= link_to "Añadir al carro", add_to_cart_path(@product) %>

<br>

<% if can? :update, @product %>
  <%= link_to 'Edit', edit_product_path(@product) %> |
<% end %>

<%= link_to 'Volver', products_path %>

app/views/purchases/purchases.html.erb
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<title></title>
	<link rel="stylesheet" href="">
</head>
<body>
	
</body>
</html>

app/views/shared/_navbar.html.erb
<p>
	<% unless user_signed_in? %>
		<%= link_to 'Ingresar', new_user_session_path %>
		<%= link_to 'Registrar', new_user_registration_path %>
	<% else %>
		<%= link_to current_user.name, edit_user_registration_path %> | <small><%= current_user.role %></small>
		<%= link_to 'Salir', destroy_user_session_path, method: :delete, data: { confirm: "Seguro que desea salir?" } %>
	<% end %>
</p>

<%= form_tag('/', method: 'get') do %>
  <%= search_field_tag :query, nil, placeholder: 'Buscar' %>
  <%= submit_tag "Buscar" %>
<% end %>
	


<script>
	$('#query').keyup(function() {
		$.ajax({
			url: '/',
			type: 'GET',
			dataType: 'script',
			data: {query: $(this).val()},
		})
	});
</script>